<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.9 setup script
 * Date: Fri, 26 Jun 2015 09:51:50 +0000
 */

/* Servers configuration */


/* Server: june [1] */
$connect_hosts = array(
            '1'=>array(
                 "host"   => "localhost",  //服务器1
                 "user"   => "admin",
                 "password" => "abc123"
                 ),
            '2' => array(
                 "host"   => "192.168.2.116", //服务器2
                 "user"   => "admin",
                 "password" => "abc123"
                 )
            );
for ($i=1;$i<=count($connect_hosts);$i++) {
	/* Authentication type */
	$cfg['Servers'][$i]['auth_type'] = 'cookie';
	/* Server parameters */
	$cfg['Servers'][$i]['host'] = $connect_hosts[$i]['host'];   //修改host
	$cfg['Servers'][$i]['connect_type'] = 'tcp';
	$cfg['Servers'][$i]['port'] = 3306;
	$cfg['Servers'][$i]['socket'] = '';
	//$cfg['Servers'][$i]['compress'] = false;
	/* Select mysqli if your server has it */
	//$cfg['Servers'][$i]['extension'] = 'mysql';
	//$cfg['Servers'][$i]['AllowNoPassword'] = true;
	$cfg['Servers'][$i]['user'] = $connect_hosts[$i]['user'];  //修改用户名
	$cfg['Servers'][$i]['password'] = $connect_hosts[$i]['password']; //密码
	/* rajk - for blobstreaming */

}

/* End of servers configuration */

$cfg['blowfish_secret'] = '558d20ac7ae635.77360103';
$cfg['DefaultLang'] = 'zh_CN';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>